version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    vendor: true
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      k8s:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      kubevirt:
        patterns:
          - "kubevirt.io/*"

  - package-ecosystem: "gomod"
    directory: "/test"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "test"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
