apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: manager-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubevirt-ipam-controller
    app.kubernetes.io/part-of: kubevirt-ipam-controller
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["kubevirt.io"]
  resources:
  - "virtualmachines"
  - "virtualmachineinstances"
  verbs: ["get", "list", "watch"]
- apiGroups: ["kubevirt.io"]
  resources:
  - "virtualmachines/finalizers"
  - "virtualmachineinstances/finalizers"
  verbs: ["update"]
- apiGroups: ["k8s.cni.cncf.io"]
  resources:
      - ipamclaims
      - network-attachment-definitions
  verbs: ["get", "list", "watch"]
- apiGroups: ["k8s.cni.cncf.io"]
  resources:
    - ipamclaims
  verbs: [ "create", "update" ]
